/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_syd_apkaddupdateserver_utils_DiffUtils */

#ifndef _Included_com_lyq_apkaddupdatedemo_utils_DiffUtils
#define _Included_com_lyq_apkaddupdatedemo_utils_DiffUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_syd_apkaddupdateserver_utils_DiffUtils
 * Method:    genDiff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_lyq_apkaddupdatedemo_utils_DiffUtils_genDiff
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
